ruby '2.5.0'
source 'https://rubygems.org'

gem 'sinatra'
gem 'sprockets'
gem 'stylus'
gem 'dalli'
gem 'memcachier'
gem 'thin'
gem 'erubis'
gem 'nestful'
gem 'closure-compiler'
gem 'yui-compressor'
gem 'rake'
gem 'uglifier'
gem 'sprockets-memcache-store', github: 'maccman/sprockets-memcache-store'
